# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [ ]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [ ]:
# TODO: Create a vector tensor
vector = torch.tensor([1,2,3,4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [ ]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1,2,3],[4,5,6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [ ]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [ ]:
# TODO: Create random tensor
random_tensor = torch.rand(4,4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.1360, 0.6903, 0.5971, 0.9696],
        [0.9792, 0.7968, 0.0687, 0.5703],
        [0.5340, 0.8588, 0.7190, 0.2468],
        [0.7789, 0.6206, 0.8457, 0.3553]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [ ]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3,224,224)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [ ]:
# TODO: Create zeros tensor
zeros = torch.zeros(5,5)

### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [ ]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(random_tensor)
ones_like

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [ ]:
# TODO: Create range tensor
range_tensor = torch.arange(0, 20, 2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [ ]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
float16_tensor
int64_tensor

tensor([1, 2, 3])

### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [ ]:
# TODO: Change dtype
float32_tensor = float16_tensor.to(torch.float32)
float32_tensor
print(float32_tensor.dtype)

torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [ ]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2,3,4)
print(info_tensor.shape, info_tensor.dtype, info_tensor.device)

torch.Size([2, 3, 4]) torch.float32 cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [ ]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5

# TODO: Subtract 10

# TODO: Multiply by 2

# TODO: Divide by 10

In [ ]:
tensor * 10

tensor([100, 200, 300])

In [ ]:
tensor - 10

tensor([ 0, 10, 20])

In [ ]:
tensor / 10

tensor([1., 2., 3.])

In [ ]:
tensor + 5

tensor([15, 25, 35])

### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [ ]:
# TODO: Create A and B
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A, B)

# TODO: Matrix mul using @
result_at = A @ B

## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [ ]:
agg_tensor = torch.arange(0, 101)
# TODO: Min

# TODO: Max

# TODO: Mean (note: may need to cast to float)

# TODO: Sum

In [ ]:
print(f"Minimum: {agg_tensor.min()}")

Minimum: 0


In [ ]:
print(f"Minimum: {agg_tensor.max()}")

Minimum: 100


In [ ]:
print(f"Minimum: {agg_tensor.float().mean()}")

Minimum: 50.0


In [ ]:
print(f"Mean: {agg_tensor.type(torch.float32).mean()}")

Mean: 50.0


In [ ]:
print(f"Sum: {agg_tensor.sum()}")

Sum: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [ ]:
# TODO: Argmin

# TODO: Argmax

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [ ]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)

### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [ ]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)

# TODO: Stack horizontally (dim=1)

### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [ ]:
import torch

tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)

# Stack vertically (dim=0)
vertical_stack = torch.cat((tensor1, tensor2), dim=0)
print("Vertical stack (dim=0):")
print(vertical_stack)

# Stack horizontally (dim=1)
horizontal_stack = torch.cat((tensor1, tensor2), dim=1)
print("\nHorizontal stack (dim=1):")
print(horizontal_stack)


Vertical stack (dim=0):
tensor([[0.3132, 0.5122],
        [0.5367, 0.1970],
        [0.2546, 0.6579],
        [0.5164, 0.2551]])

Horizontal stack (dim=1):
tensor([[0.3132, 0.5122, 0.2546, 0.6579],
        [0.5367, 0.1970, 0.5164, 0.2551]])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [ ]:

image_tensor = torch.rand(3, 100, 100)

# Permute from (C, H, W) → (H, W, C)
permuted = image_tensor.permute(1, 2, 0)

print("Original shape:", image_tensor.shape)
print("Permuted shape:", permuted.shape)


Original shape: torch.Size([3, 100, 100])
Permuted shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [ ]:
index_tensor = torch.tensor([[[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]]])

# Get 5
value = index_tensor[0, 1, 1]
print("Value:", value)

# Get second row [4, 5, 6]
second_row = index_tensor[0, 1]
print("Second row:", second_row)


Value: tensor(5)
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [ ]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)

print("Tensor:", from_numpy)

Tensor: tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [ ]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()

print("NumPy array:", to_numpy)

NumPy array: [5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [ ]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2, 2)

# Check equality
print(rand1 == rand2)

tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [ ]:
# TODO: Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

Using device: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [ ]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor =  torch.tensor([10, 20, 30])

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()
print("Back on CPU as NumPy array:", cpu_numpy)

Back on CPU as NumPy array: [10 20 30]
